In [26]:
import pandas as pd
import numpy as np

In [27]:
df=pd.read_csv("../data/raw/HR_Job_Placement_Dataset.csv")

In [28]:
df.head(15)

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,...,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status
0,27,Male,65.061656,83.842578,75.856526,Computer Science,58.221909,89.566305,64.474484,79.548913,...,5.805850,Tier 3,Not Matched,Medium,Not Required,15.0,No,18.0,Not Willing,Not Placed
1,24,Male,67.885626,64.973305,73.093588,Electronics,71.927978,54.591971,61.077306,73.316134,...,10.807739,Tier 1,Matched,High,Required,0.0,NaN,NaN,Not Willing,Not Placed
2,33,Female,73.892471,68.834121,90.196460,Information Technology,72.445041,58.587088,79.494739,75.466980,...,5.476839,Tier 3,Not Matched,Low,Not Required,0.0,No,3.0,Not Willing,Placed
3,31,Male,74.145568,76.255126,75.586731,Mechanical,78.855676,61.022065,53.740386,73.676449,...,9.980580,Tier 2,Matched,Low,Not Required,0.0,Yes,6.0,NaN,Not Placed
4,28,Male,60.475937,65.786336,80.801010,Information Technology,68.286776,65.713731,61.438314,88.994847,...,8.921233,Tier 2,Matched,Medium,Not Required,0.0,No,3.0,Willing,Not Placed
5,33,Female,60.641768,66.151843,78.203455,Others,85.063940,46.293090,47.638858,78.307411,...,3.000000,Tier 2,Not Matched,Low,Not Required,60.0,No,0.0,Not Willing,Placed
6,25,Female,78.224191,69.578282,79.870959,Mechanical,85.168067,47.188328,70.348778,79.935956,...,7.114406,Tier 2,Matched,Low,Not Required,0.0,No,0.0,Not Willing,Placed
7,27,Female,NaN,69.111350,75.430679,Others,75.672196,56.391743,76.383155,77.546335,...,3.103734,Tier 1,Matched,Medium,Not Required,0.0,No,0.0,Not Willing,Placed
8,30,Female,69.535754,78.757507,79.757543,Mechanical,78.282823,62.647484,81.629846,67.931840,...,3.000000,Tier 3,Matched,Low,Not Required,NaN,No,0.0,NaN,Placed
9,23,female,70.972461,78.101606,72.767897,Mechanical,54.554258,61.055905,59.567957,95.125145,...,3.091102,Tier 1,Not Matched,High,Required,0.0,No,0.0,Willing,Not Placed
10,27,Male,81.740922,84.465410,67.321761,Electronics,76.437526,58.922815,59.710614,68.009111,...,4.400834,Tier 3,Matched,Medium,Not Required,60.0,No,6.0,Not Willing,Not Placed
11,31,Female,80.585015,89.820812,66.437489,Information Technology,64.542507,66.739564,80.147763,80.050809,...,3.000000,Tier 1,Not Matched,Medium,Not Required,15.0,No,18.0,Willing,Not Placed
12,31,Female,72.733744,74.350728,76.396765,Others,85.602155,58.459018,77.107255,74.435967,...,3.708885,Tier 3,Matched,Low,Required,90.0,No,3.0,Willing,Not Placed
13,28,Male,64.600706,NaN,76.595184,Computer Science,63.320951,69.529122,69.894391,74.861257,...,12.339071,Tier 2,Matched,High,Not Required,30.0,No,0.0,NaN,Placed
14,25,Male,88.516513,71.517299,74.026919,Electronics,60.060036,63.699078,60.432547,66.558216,...,6.341400,Tier 3,Not Matched,Medium,Required,30.0,No,0.0,NaN,Not Placed

In [29]:
df.tail(10)

,age_years,gender,ssc_percentage,hsc_percentage,degree_percentage,degree_specialization,technical_score,aptitude_score,communication_score,skills_match_percentage,...,expected_ctc_lpa,company_tier,job_role_match,competition_level,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status
51490,23,Female,66.389543,71.804002,71.711391,Electronics,65.655161,86.448670,61.438677,71.623982,...,9.041124,Tier 3,Matched,Low,Not Required,90.0,No,0.0,Not Willing,Placed
51491,26,Female,68.845365,75.808474,64.878803,Computer Science,74.765058,58.997111,55.769771,61.490815,...,9.099572,Tier 1,Matched,Medium,Required,0.0,No,12.0,Not Willing,Not Placed
51492,23,Female,64.420976,80.759113,69.340480,Mechanical,46.707498,66.843322,68.341317,77.311556,...,13.007079,Tier 1,Matched,Low,Not Required,0.0,No,0.0,NaN,Not Placed
51493,25,Female,62.551225,87.770434,75.760378,Others,75.499660,57.339417,80.125196,89.676590,...,9.502040,Tier 2,Matched,High,Not Required,0.0,No,0.0,Willing,Placed
51494,26,Female,69.562323,63.891266,75.931809,Computer Science,59.990409,51.169120,73.769113,68.913006,...,7.910303,Tier 2,NaN,Medium,Not Required,0.0,No,6.0,Not Willing,Not Placed
51495,24,Female,65.747180,72.063946,72.247881,Electronics,55.923057,73.208032,69.108895,63.992488,...,6.315211,Tier 1,Matched,Low,Required,0.0,No,3.0,NaN,Not Placed
51496,22,Male,61.921459,66.729203,55.000000,Others,69.525121,70.245612,54.959868,88.514232,...,8.655391,Tier 1,Matched,Medium,Not Required,60.0,No,0.0,Not Willing,Placed
51497,30,Male,75.578202,75.717623,75.048301,Information Technology,73.073239,58.870416,71.219454,79.326789,...,11.538547,Tier 1,Matched,High,Not Required,0.0,No,12.0,NaN,Placed
51498,29,Female,77.327209,56.629227,69.735374,Mechanical,48.270078,61.171900,71.650243,76.318681,...,9.617279,Tier 2,Matched,Medium,Not Required,0.0,Yes,0.0,Willing,Not Placed
51499,26,Female,60.228166,73.374538,70.198897,Information Technology,76.417668,77.979750,50.369813,88.475880,...,6.346281,Tier 3,NaN,Medium,Not Required,60.0,No,0.0,Not Willing,Placed

In [30]:
df.shape

(51500, 26)

In [31]:
df.columns

Index(['age_years', 'gender', 'ssc_percentage', 'hsc_percentage',
       'degree_percentage', 'degree_specialization', 'technical_score',
       'aptitude_score', 'communication_score', 'skills_match_percentage',
       'certifications_count', 'internship_experience', 'years_of_experience',
       'career_switch_willingness', 'relevant_experience', 'previous_ctc_lpa',
       'expected_ctc_lpa', 'company_tier', 'job_role_match',
       'competition_level', 'bond_requirement', 'notice_period_days',
       'layoff_history', 'employment_gap_months', 'relocation_willingness',
       'status'],
      dtype='str')

In [32]:
df.dtypes

age_years                      int64
gender                           str
ssc_percentage               float64
hsc_percentage               float64
degree_percentage            float64
degree_specialization            str
technical_score              float64
aptitude_score               float64
communication_score          float64
skills_match_percentage      float64
certifications_count           int64
internship_experience            str
years_of_experience            int64
career_switch_willingness        str
relevant_experience              str
previous_ctc_lpa             float64
expected_ctc_lpa             float64
company_tier                     str
job_role_match                   str
competition_level                str
bond_requirement                 str
notice_period_days           float64
layoff_history                   str
employment_gap_months        float64
relocation_willingness           str
status                           str
dtype: object

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51500 entries, 0 to 51499
Data columns (total 26 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age_years                  51500 non-null  int64
 1   gender                     51500 non-null  str
 2   ssc_percentage             48919 non-null  float64
 3   hsc_percentage             49435 non-null  float64
 4   degree_percentage          51500 non-null  float64
 5   degree_specialization      51500 non-null  str
 6   technical_score            51500 non-null  float64
 7   aptitude_score             51500 non-null  float64
 8   communication_score        51500 non-null  float64
 9   skills_match_percentage    51500 non-null  float64
 10  certifications_count       51500 non-null  int64
 11  internship_experience      51500 non-null  str
 12  years_of_experience        51500 non-null  int64
 13  career_switch_willingness  43034 non-null  str
 14  relevant_experience        43074 non-null  str
 15  previous_ctc_lpa           51500 non-null  float64
 16  expected_ctc_lpa           51500 non-null  float64
 17  company_tier               51500 non-null  str
 18  job_role_match             45369 non-null  str
 19  competition_level          51500 non-null  str
 20  bond_requirement           51500 non-null  str
 21  notice_period_days         49918 non-null  float64
 22  layoff_history             43033 non-null  str
 23  employment_gap_months      50403 non-null  float64
 24  relocation_willingness     43025 non-null  str
 25  status                     51500 non-null  str
dtypes: float64(11), int64(3), str(12)
memory usage: 10.2 MB

In [34]:
df.describe()

,age_years,ssc_percentage,hsc_percentage,degree_percentage,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,years_of_experience,previous_ctc_lpa,expected_ctc_lpa,notice_period_days,employment_gap_months
count,51500.000000,48919.000000,49435.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,49918.000000,50403.000000
mean,27.505456,70.002505,72.060636,74.010825,68.027499,64.005715,66.106692,73.937491,1.400136,1.494117,4.844616,8.002649,20.095457,3.056187
std,4.025385,7.976314,7.916654,6.945579,11.855145,9.922397,9.907488,11.794258,1.184387,1.375508,2.125294,3.133792,24.852660,4.431784
min,21.000000,50.000000,50.000000,55.000000,40.000000,40.000000,45.000000,45.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000
25%,24.000000,64.574733,66.720058,69.305041,59.935988,57.204237,59.252271,65.851924,1.000000,0.000000,3.325635,5.672655,0.000000,0.000000
50%,27.000000,69.971210,72.014383,73.998187,67.986042,63.972079,66.033268,74.001772,1.000000,1.000000,4.807598,7.857337,15.000000,0.000000
75%,31.000000,75.389057,77.389894,78.707827,76.049235,70.727134,72.840985,82.112773,2.000000,2.000000,6.297570,10.093509,30.000000,6.000000
max,34.000000,95.000000,95.000000,95.000000,100.000000,100.000000,100.000000,100.000000,8.000000,5.000000,13.844566,26.524634,90.000000,18.000000

In [35]:
df.isnull().sum()

age_years                       0
gender                          0
ssc_percentage               2581
hsc_percentage               2065
degree_percentage               0
degree_specialization           0
technical_score                 0
aptitude_score                  0
communication_score             0
skills_match_percentage         0
certifications_count            0
internship_experience           0
years_of_experience             0
career_switch_willingness    8466
relevant_experience          8426
previous_ctc_lpa                0
expected_ctc_lpa                0
company_tier                    0
job_role_match               6131
competition_level               0
bond_requirement                0
notice_period_days           1582
layoff_history               8467
employment_gap_months        1097
relocation_willingness       8475
status                          0
dtype: int64

In [36]:
df.isnull().mean() * 100

age_years                     0.000000
gender                        0.000000
ssc_percentage                5.011650
hsc_percentage                4.009709
degree_percentage             0.000000
degree_specialization         0.000000
technical_score               0.000000
aptitude_score                0.000000
communication_score           0.000000
skills_match_percentage       0.000000
certifications_count          0.000000
internship_experience         0.000000
years_of_experience           0.000000
career_switch_willingness    16.438835
relevant_experience          16.361165
previous_ctc_lpa              0.000000
expected_ctc_lpa              0.000000
company_tier                  0.000000
job_role_match               11.904854
competition_level             0.000000
bond_requirement              0.000000
notice_period_days            3.071845
layoff_history               16.440777
employment_gap_months         2.130097
relocation_willingness       16.456311
status                        0.000000
dtype: float64

In [37]:
df.duplicated().sum()

np.int64(1376)

In [38]:
df.describe(include='string')

,gender,degree_specialization,internship_experience,career_switch_willingness,relevant_experience,company_tier,job_role_match,competition_level,bond_requirement,layoff_history,relocation_willingness,status
count,51500,51500,51500,43034,43074,51500,45369,51500,51500,43033,43025,51500
unique,4,5,4,2,2,6,2,3,2,2,2,2
top,Female,Others,No,Not Willing,Relevant,Tier 1,Matched,Low,Not Required,No,Willing,Not Placed
freq,24379,10463,25607,28479,26305,19046,33456,21414,40231,37355,27817,35921

In [41]:
df["status"].value_counts()

status
Not Placed    35921
Placed        15579
Name: count, dtype: int64

In [42]:
df["status"].value_counts(normalize=True)

status
Not Placed    0.697495
Placed        0.302505
Name: proportion, dtype: float64

In [51]:
for col in df.select_dtypes(include='string').columns:
    print(col)
    print(df[col].value_counts())

gender
gender
Female    24379
Male      24028
male       1549
female     1544
Name: count, dtype: int64
degree_specialization
degree_specialization
Others                    10463
Electronics               10358
Information Technology    10298
Computer Science          10210
Mechanical                10171
Name: count, dtype: int64
internship_experience
internship_experience
No      25607
Yes     23327
 no      1341
yes      1225
Name: count, dtype: int64
career_switch_willingness
career_switch_willingness
Not Willing    28479
Willing        14555
Name: count, dtype: int64
relevant_experience
relevant_experience
Relevant        26305
Not Relevant    16769
Name: count, dtype: int64
company_tier
company_tier
Tier 1     19046
Tier 2     18301
Tier 3     12061
Tier 1       832
Tier 2       755
Tier 3       505
Name: count, dtype: int64
job_role_match
job_role_match
Matched        33456
Not Matched    11913
Name: count, dtype: int64
competition_level
competition_level
Low       21414
Medium    19708
High      10378
Name: count, dtype: int64
bond_requirement
bond_requirement
Not Required    40231
Required        11269
Name: count, dtype: int64
layoff_history
layoff_history
No     37355
Yes     5678
Name: count, dtype: int64
relocation_willingness
relocation_willingness
Willing        27817
Not Willing    15208
Name: count, dtype: int64
status
status
Not Placed    35921
Placed        15579
Name: count, dtype: int64