In [392]:
import pandas as pd
import numpy as np

df=pd.read_csv("../data/raw/HR_Job_Placement_Dataset.csv")

In [393]:
cleaning_col=df[['internship_experience','layoff_history','company_tier','job_role_match','relevant_experience','career_switch_willingness','bond_requirement','relocation_willingness','competition_level','status']].columns

In [394]:
for col in cleaning_col:
    df[col] = df[col].astype(str).str.strip().str.lower()

In [395]:
num_cols=df[['ssc_percentage','hsc_percentage','notice_period_days','employment_gap_months']].columns

In [396]:
for col in num_cols:
    df[col]=df[col].fillna(df[col].median())

In [397]:
cat_col=df[['career_switch_willingness','relevant_experience','job_role_match','layoff_history','relocation_willingness']].columns

In [398]:
for col in cat_col:
    df[col] = df[col].replace('nan', np.nan)

In [399]:
for col in cat_col:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

In [400]:
label_en=df[['internship_experience','layoff_history']].columns

In [401]:
for col in label_en:
    df[col] = df[col].map({"yes": 1, "no": 0})

In [402]:
df['career_switch_willingness']=df['career_switch_willingness'].map({"willing": 1, "not willing": 0})

In [403]:
df["job_role_match"]=df["job_role_match"].map({"matched": 1, "not matched": 0})

In [404]:
df['bond_requirement']=df['bond_requirement'].map({"required": 1, "not required": 0})

In [405]:
df['relevant_experience']=df['relevant_experience'].map({"relevant": 1, "not relevant": 0})

In [406]:
df['relocation_willingness']=df['relocation_willingness'].map({"willing": 1, "not willing": 0})

In [407]:
df['status']=df['status'].map({"placed": 1, "not placed": 0})

In [408]:
df['competition_level']=df['competition_level'].map({"high": 2, "medium": 1, "low": 0})

In [409]:
df['company_tier']=df['company_tier'].map({"tier 1": 1, "tier 2": 2, "tier 3": 3})

In [410]:
df = pd.get_dummies(df, columns=['degree_specialization'], drop_first=True)

In [411]:
df.columns.tolist()

['age_years',
 'gender',
 'ssc_percentage',
 'hsc_percentage',
 'degree_percentage',
 'technical_score',
 'aptitude_score',
 'communication_score',
 'skills_match_percentage',
 'certifications_count',
 'internship_experience',
 'years_of_experience',
 'career_switch_willingness',
 'relevant_experience',
 'previous_ctc_lpa',
 'expected_ctc_lpa',
 'company_tier',
 'job_role_match',
 'competition_level',
 'bond_requirement',
 'notice_period_days',
 'layoff_history',
 'employment_gap_months',
 'relocation_willingness',
 'status',
 'degree_specialization_Electronics',
 'degree_specialization_Information Technology',
 'degree_specialization_Mechanical',
 'degree_specialization_Others']

In [412]:
deg_spec_col=df[['degree_specialization_Electronics','degree_specialization_Information Technology','degree_specialization_Mechanical','degree_specialization_Others']].columns

In [413]:
print(df[deg_spec_col].dtypes)

degree_specialization_Electronics               bool
degree_specialization_Information Technology    bool
degree_specialization_Mechanical                bool
degree_specialization_Others                    bool
dtype: object

In [414]:
df[deg_spec_col] = df[deg_spec_col].astype(int)

In [415]:
df = df.drop('gender', axis=1)

In [416]:
df.head(10)

,age_years,ssc_percentage,hsc_percentage,degree_percentage,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,...,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status,degree_specialization_Electronics,degree_specialization_Information Technology,degree_specialization_Mechanical,degree_specialization_Others
0,27,65.061656,83.842578,75.856526,58.221909,89.566305,64.474484,79.548913,2,0,...,0,15.0,0,18.0,0,0,0,0,0,0
1,24,67.885626,64.973305,73.093588,71.927978,54.591971,61.077306,73.316134,1,1,...,1,0.0,0,0.0,0,0,1,0,0,0
2,33,73.892471,68.834121,90.196460,72.445041,58.587088,79.494739,75.466980,1,1,...,0,0.0,0,3.0,0,1,0,1,0,0
3,31,74.145568,76.255126,75.586731,78.855676,61.022065,53.740386,73.676449,2,0,...,0,0.0,1,6.0,1,0,0,0,1,0
4,28,60.475937,65.786336,80.801010,68.286776,65.713731,61.438314,88.994847,1,0,...,0,0.0,0,3.0,1,0,0,1,0,0
5,33,60.641768,66.151843,78.203455,85.063940,46.293090,47.638858,78.307411,1,1,...,0,60.0,0,0.0,0,1,0,0,0,1
6,25,78.224191,69.578282,79.870959,85.168067,47.188328,70.348778,79.935956,1,1,...,0,0.0,0,0.0,0,1,0,0,1,0
7,27,69.971210,69.111350,75.430679,75.672196,56.391743,76.383155,77.546335,0,1,...,0,0.0,0,0.0,0,1,0,0,0,1
8,30,69.535754,78.757507,79.757543,78.282823,62.647484,81.629846,67.931840,3,1,...,0,15.0,0,0.0,1,1,0,0,1,0
9,23,70.972461,78.101606,72.767897,54.554258,61.055905,59.567957,95.125145,0,0,...,1,0.0,0,0.0,1,0,0,0,1,0

In [417]:
df.to_csv("../data/cleaned/cleaned_unscaled.csv", index=False)

In [418]:
df[['age_years',
'ssc_percentage',
'hsc_percentage',
'degree_percentage',
'technical_score',
'aptitude_score',
'communication_score',
'skills_match_percentage',
'certifications_count',
'years_of_experience',
'previous_ctc_lpa',
'expected_ctc_lpa',
'notice_period_days',
'employment_gap_months']].describe()

,age_years,ssc_percentage,hsc_percentage,degree_percentage,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,years_of_experience,previous_ctc_lpa,expected_ctc_lpa,notice_period_days,employment_gap_months
count,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000,51500.000000
mean,27.505456,70.000936,72.058781,74.010825,68.027499,64.005715,66.106692,73.937491,1.400136,1.494117,4.844616,8.002649,19.938932,2.991087
std,4.025385,7.773871,7.756315,6.945579,11.855145,9.922397,9.907488,11.794258,1.184387,1.375508,2.125294,3.133792,24.483750,4.406479
min,21.000000,50.000000,50.000000,55.000000,40.000000,40.000000,45.000000,45.000000,0.000000,0.000000,1.000000,3.000000,0.000000,0.000000
25%,24.000000,64.899006,66.974815,69.305041,59.935988,57.204237,59.252271,65.851924,1.000000,0.000000,3.325635,5.672655,0.000000,0.000000
50%,27.000000,69.971210,72.014383,73.998187,67.986042,63.972079,66.033268,74.001772,1.000000,1.000000,4.807598,7.857337,15.000000,0.000000
75%,31.000000,75.066581,77.133064,78.707827,76.049235,70.727134,72.840985,82.112773,2.000000,2.000000,6.297570,10.093509,30.000000,6.000000
max,34.000000,95.000000,95.000000,95.000000,100.000000,100.000000,100.000000,100.000000,8.000000,5.000000,13.844566,26.524634,90.000000,18.000000

In [419]:
scaling_col=df[['age_years',
'ssc_percentage',
'hsc_percentage',
'degree_percentage',
'technical_score',
'aptitude_score',
'communication_score',
'skills_match_percentage',
'certifications_count',
'years_of_experience',
'previous_ctc_lpa',
'expected_ctc_lpa',
'notice_period_days',
'employment_gap_months']].columns

In [420]:

from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler

In [421]:
scaler = StandardScaler()
df[scaling_col] = scaler.fit_transform(df[scaling_col])

In [422]:
df.head(10)

,age_years,ssc_percentage,hsc_percentage,degree_percentage,technical_score,aptitude_score,communication_score,skills_match_percentage,certifications_count,internship_experience,...,bond_requirement,notice_period_days,layoff_history,employment_gap_months,relocation_willingness,status,degree_specialization_Electronics,degree_specialization_Information Technology,degree_specialization_Mechanical,degree_specialization_Others
0,-0.125568,-0.635376,1.519267,0.265740,-0.827125,2.576075,-0.164746,0.475780,0.506481,0,...,0,-0.201725,0,3.406134,0,0,0,0,0,0
1,-0.870846,-0.272108,-0.913519,-0.132062,0.329015,-0.948746,-0.507640,-0.052684,-0.337845,1,...,1,-0.814382,0,-0.678800,0,0,1,0,0,0
2,1.364987,0.500596,-0.415750,2.330373,0.372630,-0.546106,1.351319,0.129682,-0.337845,1,...,0,-0.814382,0,0.002023,0,1,0,1,0,0
3,0.868135,0.533154,0.541028,0.226896,0.913382,-0.300701,-1.248190,-0.022133,0.506481,0,...,0,-0.814382,1,0.682845,1,0,0,0,1,0
4,0.122857,-1.225270,-0.808697,0.977636,0.021871,0.172139,-0.471201,1.276681,-0.337845,0,...,0,-0.814382,0,0.002023,1,0,0,1,0,0
5,1.364987,-1.203938,-0.761572,0.603646,1.437064,-1.785133,-1.864046,0.370516,-0.337845,1,...,0,1.636247,0,-0.678800,0,1,0,0,0,1
6,-0.622420,1.057817,-0.319807,0.843730,1.445848,-1.694908,0.428174,0.508597,-0.337845,1,...,0,-0.814382,0,-0.678800,0,1,0,0,1,0
7,-0.125568,-0.003824,-0.380008,0.204428,0.644848,-0.767360,1.037252,0.305986,-1.182172,1,...,0,-0.814382,0,-0.678800,0,1,0,0,0,1
8,0.619709,-0.059840,0.863656,0.827400,0.865061,-0.136887,1.566826,-0.509206,1.350808,1,...,0,-0.201725,0,-0.678800,1,1,0,0,1,0
9,-1.119272,0.124974,0.779092,-0.178954,-1.136500,-0.297291,-0.659985,1.796455,-1.182172,0,...,1,-0.814382,0,-0.678800,1,0,0,0,1,0

In [423]:
df.to_csv("../data/cleaned/cleaned_data.csv", index=False)